name: env2dart
description: A simple way to generate `dart` code from a `.env` file.
version: 0.3.7
homepage: https://github.com/fluttercandies
repository: https://github.com/fluttercandies/env2dart
issue_tracker: https://github.com/fluttercandies/env2dart/issues

environment:
  sdk: '>=2.15.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  antlr4: ^4.12.0
  args: ^2.4.0
  built_collection: ^5.1.1
  built_value: ^8.4.4
  code_builder: ^4.4.0
  collection: ^1.17.1
  dart_style: ^2.3.0
  dolumns: ^2.0.0
  path: ^1.8.3
  recase: ^4.1.0

executables:
  env2dart: env2dart
